apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-jenkins-project.fullname" . }}
  labels:
    {{- include "helm-jenkins-project.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if and (eq .Values.service.type "LoadBalancer") .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- with .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
    {{- if .Values.service.exposeAgent }}
    - name: agent
      port: {{ .Values.service.agentPort }}
      targetPort: agent
      protocol: TCP
      {{- if and (eq .Values.service.type "NodePort") .Values.service.agentNodePort }}
      nodePort: {{ .Values.service.agentNodePort }}
      {{- end }}
    {{- end }}
    {{- with .Values.service.extraPorts }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  selector:
    {{- include "helm-jenkins-project.selectorLabels" . | nindent 4 }}

